language: ruby
cache: bundler

addons:
  postgresql: "9.4"

services: postgresql

install:
  - bundle config set --local path 'vendor/bundle'
  - bundle install
  - bin/setup

script:
  - bundle exec rubocop --parallel
  - bundle exec rspec
