language: ruby
cache: bundler

addons:
  postgresql: "9.4"

services: postgresql

install:
  - bundle install --path vendor/bundle
  - bin/setup

script:
  - bundle exec rubocop --parallel
  - bundle exec rspec
