version: '3.1'

services:
  db:
    image: postgres:9.4
    container_name: atomic_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-atomic}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_HOST: ${DB_HOST:-localhost}
      POSTGRES_PORT: ${DB_PORT:-5432}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
