#!/usr/bin/env bash

set -Eeuo pipefail

BASE_DIR=$(dirname "${BASH_SOURCE[0]:-$0}")
cd "${BASE_DIR}/.." || exit 127

# shellcheck source=../scripts/helpers.sh
. scripts/helpers.sh
# shellcheck source=../scripts/logging.sh
. scripts/logging.sh
# shellcheck source=../scripts/utils.sh
. scripts/utils.sh

PROGRAM=$(basename "${BASH_SOURCE[0]:-$0}")
VERSION=0.5.4

function display_help() {
  cat <<EOF
  $(help_title_section Usage)
    ${PROGRAM} [options] <command>

  $(help_title_section Commands)
    docker             Start development server from a docker container [default command].
    local              Start development server in your own machine.

  $(help_title_section Options)
    -h --help         Show this screen.
    -v --version      Show version.
EOF
}

case ${1:-docker} in
  -h | --help)
    display_help
    ;;
  -v | --version)
    display_version "${VERSION}" "${PROGRAM}"
    ;;
  docker)
    docker-compose -f docker-compose.dev.yml up -d
    ;;
  local)
    mix phx.server
    ;;
  *)
    display_help >&2
    exit 1
    ;;
esac
